### ISSUE TITLE
Umbrella issue for feature parity

### ISSUE THREAD

**Issue by SaraVieira** [axodotdev/oranda#24]
- [x] file → Your Readme.md name  
- [x] name → The project name that is in the title and the header  
- [x] logo → Link to your logo image, can be relative or absolute
- [x] description → The project description for meta tags     
- [x] shareCard → URL to social media preview image for meta tags (recommended size: 1200x628, URL cannot be relative) , impl https://github.com/axodotdev/oranda-js/blob/main/src/utils/head.js#L59
- [x] homepage →The project homepage for meta tags  (https://github.com/axodotdev/oranda/pull/30)
- [x] noHeader → Show no header and just the markdown content  impl https://github.com/axodotdev/oranda-js/blob/main/src/utils/header.js#L20
- [x] theme → Options are `light`, `dark`and `axo`     
- [x] syntaxHighlight → What syntax highlight theme to use in dark and light mode
- [x] favicon  → Favicon url or local path (impl https://github.com/axodotdev/oranda-js/blob/main/src/utils/head.js#L31)
- [x] dist → what folder to export your HTML   
- [x] styles → path to css/scss file (https://github.com/axodotdev/oranda/pull/23)                       
- [x] additionalFiles → Any other pages to create. It expects an array of paths of markdown files    
- [x] repository → Link to point the github corner  (https://github.com/axodotdev/oranda/pull/31)
- [x] pathPrefix → Host your oranda files at e.g. /my-oranda-project (impl https://github.com/axodotdev/oranda-js/blob/main/src/utils/header.js#L14)
- [ ] downloads → Links to download binaries or ways to install package, example below 
	Implementation:
	- 	https://github.com/axodotdev/oranda-js/blob/main/src/utils/createTabs.js
	- https://github.com/axodotdev/oranda-js/blob/main/src/commands/oranda.js#L95

Dropped

- [ ] ~~meta → Any extra meta tags you would like~~ 
- [ ]  ~~remoteScripts → Array of any remote scripts you want to include (eg: Google Analytics)~~
- [ ]  ~~remoteStyles → Array of any remote styles you want to include (eg: Google Fonts)~~

**Comment by ashleygwilliams** [comment]
one box left! do we want to close this and open an issue for the final box (downloads)?

**Comment by SaraVieira** [comment]
Yas! I'll close it as soon as the path prefix is merged :)

**Comment by SaraVieira** [comment]
closed by https://github.com/axodotdev/oranda/issues/24
