### ISSUE TITLE
Platform-specific package managers

### ISSUE THREAD

**Issue by manyinsects** [axodotdev/oranda#604]
Currently, all of our package managers are global. This means that they'll be shown for every arch/target. This is fine for a lot of package managers, such as npm or Cargo, but there are also _lots_ of platform-specific ones, including:

- Homebew, for macOS
- apt/yum/dnf/zypper/pacman/you name it for Linux
- scoop for Windows

...and way more. Package managers should therefore be able to have a platform scope attached to them, only showing up on the platforms they actually support.

## To-Do

- [ ] Etch out configuration design (@ashleygwilliams made an interesting point - package manager declaration is effectively _data_, not _config_, maybe it should live in a different file/space?)
- [ ] Handle Homebrew correctly - `cargo-dist` returns a `[name].rb` file that we need to properly rename
- [ ] Implement a general version
